### ISSUE TITLE
web版本编译报错

### ISSUE THREAD

**Issue by hugetiny** [niuhuan/pikapika#139]
浏览器：edge最新版

```
DEPTH : 1
Error: Unsupported operation: Platform._operatingSystem
    at Object.throw_ [as throw] (http://localhost:51836/dart_sdk.js:5069:11)
    at Function._operatingSystem (http://localhost:51836/dart_sdk.js:57603:17)
    at Function.get operatingSystem [as operatingSystem] (http://localhost:51836/dart_sdk.js:57649:27)
    at get _operatingSystem (http://localhost:51836/dart_sdk.js:57562:27)
    at Function.desc.get [as _operatingSystem] (http://localhost:51836/dart_sdk.js:5562:17)
    at get isAndroid (http://localhost:51836/dart_sdk.js:57583:26)
    at Function.desc.get [as isAndroid] (http://localhost:51836/dart_sdk.js:5562:17)
    at initPlatform (http://localhost:51836/packages/pikapika/basic/config/Platform.dart.lib.js:16:23)
    at initPlatform.next (<anonymous>)
    at runBody (http://localhost:51836/dart_sdk.js:40646:34)
    at Object._async [as async] (http://localhost:51836/dart_sdk.js:40677:7)
    at Object.initPlatform (http://localhost:51836/packages/pikapika/basic/config/Platform.dart.lib.js:15:18)
    at InitScreen._InitScreenState.new._init (http://localhost:51836/packages/pikapika/screens/InitScreen.dart.lib.js:330:24)
    at _init.next (<anonymous>)
    at runBody (http://localhost:51836/dart_sdk.js:40646:34)
    at Object._async [as async] (http://localhost:51836/dart_sdk.js:40677:7)
    at InitScreen._InitScreenState.new.[_init] (http://localhost:51836/packages/pikapika/screens/InitScreen.dart.lib.js:329:20)
    at InitScreen._InitScreenState.new.initState (http://localhost:51836/packages/pikapika/screens/InitScreen.dart.lib.js:325:18)
    at framework.StatefulElement.new.[_firstBuild] (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:52680:54)
    at framework.StatefulElement.new.mount (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:24984:26)
    at framework.SingleChildRenderObjectElement.new.inflateWidget (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:23857:16)
    at framework.SingleChildRenderObjectElement.new.updateChild (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:23710:25)
    at framework.SingleChildRenderObjectElement.new.mount (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:33631:29)
    at framework.StatelessElement.new.inflateWidget (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:23857:16)
    at framework.StatelessElement.new.updateChild (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:23710:25)
    at framework.StatelessElement.new.performRebuild (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:25021:31)
    at framework.StatelessElement.new.rebuild (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:24218:12)
    at framework.StatelessElement.new.[_firstBuild] (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:24988:12)
    at framework.StatelessElement.new.mount (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:24984:26)
    at framework.SingleChildRenderObjectElement.new.inflateWidget (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:23857:16)
    at framework.SingleChildRenderObjectElement.new.updateChild (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:23710:25)
    at framework.SingleChildRenderObjectElement.new.mount (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:33631:29)
    at framework.SingleChildRenderObjectElement.new.inflateWidget (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:23857:16)
    at framework.SingleChildRenderObjectElement.new.updateChild (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:23710:25)
    at framework.SingleChildRenderObjectElement.new.mount (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:33631:29)
    at framework.StatefulElement.new.inflateWidget (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:23857:16)
    at framework.StatefulElement.new.updateChild (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:23710:25)
    at framework.StatefulElement.new.performRebuild (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:25021:31)
    at framework.StatefulElement.new.performRebuild (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:52706:13)
    at framework.StatefulElement.new.rebuild (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:24218:12)
    at framework.StatefulElement.new.[_firstBuild] (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:24988:12)
    at framework.StatefulElement.new.[_firstBuild] (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:52699:27)
    at framework.StatefulElement.new.mount (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:24984:26)
    at framework.SingleChildRenderObjectElement.new.inflateWidget (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:23857:16)
    at framework.SingleChildRenderObjectElement.new.updateChild (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:23710:25)
    at framework.SingleChildRenderObjectElement.new.mount (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:33631:29)
    at framework.SingleChildRenderObjectElement.new.inflateWidget (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:23857:16)
    at framework.SingleChildRenderObjectElement.new.updateChild (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:23710:25)
    at framework.SingleChildRenderObjectElement.new.mount (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:33631:29)
    at framework.StatefulElement.new.inflateWidget (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:23857:16)
    at framework.StatefulElement.new.updateChild (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:23710:25)
    at framework.StatefulElement.new.performRebuild (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:25021:31)
    at framework.StatefulElement.new.performRebuild (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:52706:13)
    at framework.StatefulElement.new.rebuild (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:24218:12)
    at framework.StatefulElement.new.[_firstBuild] (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:24988:12)
    at framework.StatefulElement.new.[_firstBuild] (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:52699:27)
    at framework.StatefulElement.new.mount (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:24984:26)
    at framework.StatelessElement.new.inflateWidget (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:23857:16)
    at framework.StatelessElement.new.updateChild (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:23710:25)
    at framework.StatelessElement.new.performRebuild (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:25021:31)
    at framework.StatelessElement.new.rebuild (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:24218:12)
    at framework.StatelessElement.new.[_firstBuild] (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:24988:12)
    at framework.StatelessElement.new.mount (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:24984:26)
    at framework.StatefulElement.new.inflateWidget (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:23857:16)
    at framework.StatefulElement.new.updateChild (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:23710:25)
    at framework.StatefulElement.new.performRebuild (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:25021:31)
    at framework.StatefulElement.new.performRebuild (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:52706:13)
    at framework.StatefulElement.new.rebuild (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:24218:12)
    at framework.StatefulElement.new.[_firstBuild] (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:24988:12)
    at framework.StatefulElement.new.[_firstBuild] (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:52699:27)
    at framework.StatefulElement.new.mount (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:24984:26)
    at framework.SingleChildRenderObjectElement.new.inflateWidget (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:23857:16)
    at framework.SingleChildRenderObjectElement.new.updateChild (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:23710:25)
    at framework.SingleChildRenderObjectElement.new.mount (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:33631:29)
    at framework.SingleChildRenderObjectElement.new.inflateWidget (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:23857:16)
    at framework.SingleChildRenderObjectElement.new.updateChild (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:23710:25)
    at framework.SingleChildRenderObjectElement.new.mount (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:33631:29)
    at _InheritedNotifierElement.new.inflateWidget (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:23857:16)
    at _InheritedNotifierElement.new.updateChild (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:23710:25)
    at _InheritedNotifierElement.new.performRebuild (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:25021:31)
    at _InheritedNotifierElement.new.rebuild (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:24218:12)
    at _InheritedNotifierElement.new.[_firstBuild] (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:24988:12)
    at _InheritedNotifierElement.new.mount (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:24984:26)
    at framework.SingleChildRenderObjectElement.new.inflateWidget (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:23857:16)
    at framework.SingleChildRenderObjectElement.new.updateChild (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:23710:25)
    at framework.SingleChildRenderObjectElement.new.mount (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:33631:29)
    at framework.StatefulElement.new.inflateWidget (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:23857:16)
    at framework.StatefulElement.new.updateChild (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:23710:25)
    at framework.StatefulElement.new.performRebuild (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:25021:31)
    at framework.StatefulElement.new.performRebuild (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:52706:13)
    at framework.StatefulElement.new.rebuild (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:24218:12)
    at framework.StatefulElement.new.[_firstBuild] (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:24988:12)
    at framework.StatefulElement.new.[_firstBuild] (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:52699:27)
    at framework.StatefulElement.new.mount (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:24984:26)
    at framework.InheritedElement.new.inflateWidget (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:23857:16)
    at framework.InheritedElement.new.updateChild (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:23710:25)
    at framework.InheritedElement.new.performRebuild (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:25021:31)
    at framework.InheritedElement.new.rebuild (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:24218:12)
    at framework.InheritedElement.new.[_firstBuild] (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:24988:12)
    at framework.InheritedElement.new.mount (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:24984:26)
    at framework.InheritedElement.new.inflateWidget (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:23857:16)
    at framework.InheritedElement.new.updateChild (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:23710:25)
    at framework.InheritedElement.new.performRebuild (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:25021:31)
    at framework.InheritedElement.new.rebuild (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:24218:12)
    at framework.InheritedElement.new.[_firstBuild] (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:24988:12)
    at framework.InheritedElement.new.mount (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:24984:26)
    at framework.StatefulElement.new.inflateWidget (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:23857:16)
    at framework.StatefulElement.new.updateChild (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:23710:25)
    at framework.StatefulElement.new.performRebuild (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:25021:31)
    at framework.StatefulElement.new.performRebuild (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:52706:13)
    at framework.StatefulElement.new.rebuild (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:24218:12)
    at framework.StatefulElement.new.[_firstBuild] (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:24988:12)
    at framework.StatefulElement.new.[_firstBuild] (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:52699:27)
    at framework.StatefulElement.new.mount (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:24984:26)
    at framework.StatelessElement.new.inflateWidget (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:23857:16)
    at framework.StatelessElement.new.updateChild (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:23710:25)
    at framework.StatelessElement.new.performRebuild (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:25021:31)
    at framework.StatelessElement.new.rebuild (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:24218:12)
    at framework.StatelessElement.new.[_firstBuild] (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:24988:12)
    at framework.StatelessElement.new.mount (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:24984:26)
    at framework.StatelessElement.new.inflateWidget (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:23857:16)
    at framework.StatelessElement.new.updateChild (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:23710:25)
    at framework.StatelessElement.new.performRebuild (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:25021:31)
    at framework.StatelessElement.new.rebuild (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:24218:12)
    at framework.StatelessElement.new.[_firstBuild] (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:24988:12)
    at framework.StatelessElement.new.mount (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:24984:26)
    at basic._OffstageElement.new.inflateWidget (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:23857:16)
    at basic._OffstageElement.new.updateChild (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:23710:25)
    at basic._OffstageElement.new.mount (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:33631:29)
    at framework.InheritedElement.new.inflateWidget (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:23857:16)
    at framework.InheritedElement.new.updateChild (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:23710:25)
    at framework.InheritedElement.new.performRebuild (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:25021:31)
    at framework.InheritedElement.new.rebuild (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:24218:12)
    at framework.InheritedElement.new.[_firstBuild] (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:24988:12)
    at framework.InheritedElement.new.mount (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:24984:26)
    at framework.InheritedElement.new.inflateWidget (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:23857:16)
    at framework.InheritedElement.new.updateChild (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:23710:25)
    at framework.InheritedElement.new.performRebuild (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:25021:31)
    at framework.InheritedElement.new.rebuild (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:24218:12)
    at framework.InheritedElement.new.[_firstBuild] (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:24988:12)
    at framework.InheritedElement.new.mount (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:24984:26)
    at framework.StatefulElement.new.inflateWidget (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:23857:16)
    at framework.StatefulElement.new.updateChild (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:23710:25)
    at framework.StatefulElement.new.performRebuild (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:25021:31)
    at framework.StatefulElement.new.performRebuild (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:52706:13)
    at framework.StatefulElement.new.rebuild (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:24218:12)
    at framework.StatefulElement.new.[_firstBuild] (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:24988:12)
    at framework.StatefulElement.new.[_firstBuild] (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:52699:27)
    at framework.StatefulElement.new.mount (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:24984:26)
    at framework.StatefulElement.new.inflateWidget (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:23857:16)
    at framework.StatefulElement.new.updateChild (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:23710:25)
    at framework.StatefulElement.new.performRebuild (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:25021:31)
    at framework.StatefulElement.new.performRebuild (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:52706:13)
    at framework.StatefulElement.new.rebuild (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:24218:12)
    at framework.StatefulElement.new.[_firstBuild] (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:24988:12)
    at framework.StatefulElement.new.[_firstBuild] (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:52699:27)
    at framework.StatefulElement.new.mount (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:24984:26)
    at framework.StatefulElement.new.inflateWidget (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:23857:16)
    at framework.StatefulElement.new.updateChild (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:23710:25)
    at framework.StatefulElement.new.performRebuild (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:25021:31)
    at framework.StatefulElement.new.performRebuild (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:52706:13)
    at framework.StatefulElement.new.rebuild (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:24218:12)
    at framework.StatefulElement.new.[_firstBuild] (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:24988:12)
    at framework.StatefulElement.new.[_firstBuild] (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:52699:27)
    at framework.StatefulElement.new.mount (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:24984:26)
    at framework.SingleChildRenderObjectElement.new.inflateWidget (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:23857:16)
    at framework.SingleChildRenderObjectElement.new.updateChild (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:23710:25)
    at framework.SingleChildRenderObjectElement.new.mount (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:33631:29)
    at framework.InheritedElement.new.inflateWidget (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:23857:16)
    at framework.InheritedElement.new.updateChild (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:23710:25)
    at framework.InheritedElement.new.performRebuild (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:25021:31)
    at framework.InheritedElement.new.rebuild (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:24218:12)
    at framework.InheritedElement.new.[_firstBuild] (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:24988:12)
    at framework.InheritedElement.new.mount (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:24984:26)
    at framework.StatefulElement.new.inflateWidget (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:23857:16)
    at framework.StatefulElement.new.updateChild (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:23710:25)
    at framework.StatefulElement.new.performRebuild (http://localhost:51836/packages/flutter/src/widgets/widget_inspector.dart.lib.js:25021:31)
    at framework.StatefulElement.new.performRebuild 
......

```

**Comment by niuhuan** [comment]
golang并不支持web
